constantColumns = ['nft_weight_nan_ratio_mean', 'nft_weight_nan_ratio_std', 'nft_weight_nan_ratio_skew',
                        'nft_weight_nan_ratio_median',
                        'nft_weight_nan_ratio_var', 'nft_weight_nan_ratio_sem', 'nft_weight_nan_ratio_max',
                        'nft_weight_nan_ratio_min', 'nft_weight_nan_ratio_last',
                        'nft_nan_gradient_ratio_mean', 'nft_nan_gradient_ratio_std', 'nft_nan_gradient_ratio_skew',
                        'nft_nan_gradient_ratio_median',
                        'nft_nan_gradient_ratio_var', 'nft_nan_gradient_ratio_sem', 'nft_nan_gradient_ratio_max',
                        'nft_nan_gradient_ratio_min',
                        'nft_nan_gradient_ratio_last', 'ft_not_converge_mean', 'ft_not_converge_std',
                        'ft_not_converge_skew', 'ft_not_converge_median',
                        'ft_not_converge_var', 'ft_not_converge_sem', 'ft_not_converge_max', 'ft_not_converge_min',
                        'ft_unstable_loss_mean', 'ft_unstable_loss_std',
                        'ft_unstable_loss_skew', 'ft_unstable_loss_median', 'ft_unstable_loss_var',
                        'ft_unstable_loss_sem', 'ft_unstable_loss_max',
                        'ft_unstable_loss_min', 'ft_test_turn_bad_mean', 'ft_test_turn_bad_std',
                        'ft_test_turn_bad_skew', 'ft_test_turn_bad_median',
                        'ft_test_turn_bad_var', 'ft_test_turn_bad_sem', 'ft_test_turn_bad_max', 'ft_test_turn_bad_min',
                        'ft_sc_accuracy_mean', 'ft_sc_accuracy_std',
                        'ft_sc_accuracy_skew', 'ft_sc_accuracy_median', 'ft_sc_accuracy_var', 'ft_sc_accuracy_sem',
                        'ft_sc_accuracy_max', 'ft_sc_accuracy_min',
                        'ft_vanish_gradient_mean', 'ft_vanish_gradient_std', 'ft_vanish_gradient_skew',
                        'ft_vanish_gradient_median', 'ft_vanish_gradient_var',
                        'ft_vanish_gradient_sem', 'ft_vanish_gradient_max', 'ft_vanish_gradient_min',
                        'ft_explode_gradient_mean', 'ft_explode_gradient_std',
                        'ft_explode_gradient_skew', 'ft_explode_gradient_median', 'ft_explode_gradient_var',
                        'ft_explode_gradient_sem', 'ft_explode_gradient_max',
                        'ft_explode_gradient_min', 'ft_nan_gradient_mean', 'ft_nan_gradient_std',
                        'ft_nan_gradient_skew', 'ft_nan_gradient_median',
                        'ft_nan_gradient_var', 'ft_nan_gradient_sem', 'ft_nan_gradient_max', 'ft_nan_gradient_min',
                        'ft_large_weight_mean', 'ft_large_weight_std',
                        'ft_large_weight_skew', 'ft_large_weight_median', 'ft_large_weight_var', 'ft_large_weight_sem',
                        'ft_large_weight_max', 'ft_large_weight_min',
                        'ft_decrease_acc_mean', 'ft_decrease_acc_std', 'ft_decrease_acc_skew', 'ft_decrease_acc_median',
                        'ft_decrease_acc_var', 'ft_decrease_acc_sem',
                        'ft_decrease_acc_max', 'ft_decrease_acc_min']

